package settings

const val AGENT_UPDATES_PER_SECOND = 15
const val PROJECTILE_UPDATES_PER_SECOND = 3
const val PICKUP_UPDATES_PER_SECOND = 3
const val SCOREBOARD_UPDATES_PER_SECOND = 1

const val MAP_OBJECTS_COUNT = 45

const val MAP_WIDTH = 6400
const val MAP_HEIGHT = 3600

const val WINDOW_WIDTH = 1280
const val WINDOW_HEIGHT = 720

const val WALL_SPRITE_WIDTH = 50
const val WALL_SPRITE_HEIGHT = 50

const val PLAYER_SPRITE_WIDTH = 56
const val PLAYER_SPRITE_HEIGHT = 65

const val ZONE_SIZE = 100

const val PLAYER_BASE_HEALTH = 200
const val INVINCIBILITY_DURATION = 5

const val PISTOL_RELOAD_TIME = 400
const val PISTOL_BULLET_SPEED = 1000f
const val PISTOL_BULLETS_IN_CHAMBER = 18
const val PISTOL_MAGAZINE_REFILL_TIME = 1300
const val PISTOL_PROJECTILE_DAMAGE = 70

const val PISTOL_SPRITE_WIDTH = 40
const val PISTOL_SPRITE_HEIGHT = 28


