package settings

const val AGENT_UPDATES_PER_SECOND = 15
const val PROJECTILE_UPDATES_PER_SECOND = 3
const val PICKUP_UPDATES_PER_SECOND = 3
const val SCOREBOARD_UPDATES_PER_SECOND = 1

const val MAP_OBJECTS_COUNT = 45

const val WEAPON_RESPAWN_RATE = 60 // seconds
const val PISTOLS_ON_MAP = 2
const val MACHINE_GUNS_ON_MAP = 7
const val SHOTGUNS_ON_MAP = 7

const val MAP_WIDTH = 6400
const val MAP_HEIGHT = 3600

const val WINDOW_WIDTH = 1280
const val WINDOW_HEIGHT = 720

const val WALL_SPRITE_WIDTH = 50
const val WALL_SPRITE_HEIGHT = 50

const val PLAYER_SPRITE_WIDTH = 56
const val PLAYER_SPRITE_HEIGHT = 65

const val PLAYER_MOVEMENT_SPEED = 200f

const val ZONE_SIZE = 100

const val PLAYER_BASE_HEALTH = 200
const val INVINCIBILITY_DURATION = 5

const val PISTOL_RELOAD_TIME = 400
const val PISTOL_BULLET_SPEED = 1000f
const val PISTOL_BULLETS_IN_CHAMBER = 18
const val PISTOL_MAGAZINE_REFILL_TIME = 1300
const val PISTOL_PROJECTILE_DAMAGE = 70f

const val PISTOL_SPRITE_WIDTH = 40
const val PISTOL_SPRITE_HEIGHT = 28

const val MACHINE_GUN_RELOAD_TIME = 100
const val MACHINE_GUN_BULLET_SPEED = 1200f
const val MACHINE_GUN_BULLETS_IN_CHAMBER = 40
const val MACHINE_GUN_MAGAZINE_REFILL_TIME = 1300
const val MACHINE_GUN_PROJECTILE_DAMAGE = 50f

const val MACHINE_GUN_SPRITE_WIDTH = 57
const val MACHINE_GUN_SPRITE_HEIGHT = 27

const val SHOTGUN_RELOAD_TIME = 550
const val SHOTGUN_BULLET_SPEED = 700f
const val SHOTGUN_BULLETS_IN_CHAMBER = 10
const val SHOTGUN_MAGAZINE_REFILL_TIME = 1300
const val SHOTGUN_PROJECTILE_DAMAGE = 25f

const val SHOTGUN_SPREAD = 15 // degrees
const val SHOTGUN_PROJECTILES_FIRED = 10

const val SHOTGUN_SPRITE_WIDTH = 45
const val SHOTGUN_SPRITE_HEIGHT = 30

const val BAZOOKA_RELOAD_TIME = 1000
const val BAZOOKA_BULLET_SPEED = 650f
const val BAZOOKA_BULLETS_IN_CHAMBER = 3
const val BAZOOKA_MAGAZINE_REFILL_TIME = 1300

const val BAZOOKA_SPRITE_WIDTH = 50
const val BAZOOKA_SPRITE_HEIGHT = 30

const val BAZOOKA_EXPLOSION_SIZE = 256
const val BAZOOKA_EXPLOSION_DAMAGE = 250

const val STANDARD_PROJECTILE_WIDTH = 14
const val BAZOOKA_PROJECTILE_WIDTH = 28


